version: '2'
services:
  app:
    build: .
    command: make run
    volumes:
      - ./src/my_go_project:/workspace/src/my_go_project
    environment:
      CODE_ENV: dev
    ports:
      - "18770:18770"
    logging:
      driver: 'json-file'
